### ISSUE TITLE
ユーザープロフィールの拡張

### ISSUE THREAD

**Issue by taxio** [jphacks/KB_1809_2#125]
追加する情報を決めるところから

**Comment by lanqiugit** [comment]
[欲しい情報]
・ユーザー名
・ユーザーアイコン
・メール
・登録日時
・投稿したデートコース名
・投稿した画像(homeで表示されている画像)
・投稿した日時
・投稿したコースに対するいいね数
・投稿したコースに対するコメント数

**Comment by pddg** [comment]
・投稿したデートコース名
・投稿した画像(homeで表示されている画像)
・投稿した日時

この3つだけよくわからないので詳細が欲しい

**Comment by lanqiugit** [comment]
ユーザーがこれまでに投稿したデートコースのデートコース名と画像と日時です.

**Comment by ken-kentan** [comment]
`/api/{version}/plans/me/` 的なものがあればできそう

**Comment by ken-kentan** [comment]
`/api/{version}/plans/{user_id}/`の方が綺麗?
`/api/{version}/users/{user_id}/plans` ?

**Comment by pddg** [comment]
そのendpointは #128 で入りました

**Comment by pddg** [comment]
@lanqiugit 1リクエストで全部の情報が取れた方が嬉しい？

**Comment by lanqiugit** [comment]
今データ取得の仕方で行き詰っているところですので,  少々お待ちください.

**Comment by lanqiugit** [comment]
ユーザ情報は無事に取れましたので, 今のところは大丈夫です.
