### ISSUE TITLE
Google MapにIntentで飛ばすためのURLを付与する

### ISSUE THREAD

**Issue by pddg** [jphacks/KB_1809_2#153]
Spotには単一のポイントを，Planには全体の経路を載せる．それぞれ `intent_url` とかで返す

**Comment by pddg** [comment]
DBにマイグレーションする際に動的に値を決定する方法

https://simpleisbetterthancomplex.com/tutorial/2017/09/26/how-to-create-django-data-migrations.html

**Comment by ken-kentan** [comment]
map_url に一票
