### ISSUE TITLE
画像サイズを最適化する

### ISSUE THREAD

**Issue by taxio** [jphacks/KB_1809_2#58]

**Comment by ken-kentan** [comment]
👍

**Comment by ken-kentan** [comment]
アイコンはPNG，画像はJPEG 80%ぐらいでどうですかね？

**Comment by taxio** [comment]
@ken-kentan 
了解．
画像保存時にいい感じに最適化する処理を入れるのですが，画像サイズ(縦横のpx数)は最大どのくらいがいいですか？

**Comment by taxio** [comment]
アス比は保持します

**Comment by taxio** [comment]
iconは最大100*100, その他画像は600*600以内で画像が保存されるようにしました．
JPEGのqualityは80%です．
