### ISSUE TITLE
favのpostを簡潔にしたい

### ISSUE THREAD

**Issue by ken-kentan** [jphacks/KB_1809_2#90]
認証トークンを持っているので fav (Boolean) と plan id をPostするだけで反映されるようにしたいです。

**Comment by ken-kentan** [comment]
> 認証トークンを持っている

User 情報をpostに含めなくても良いのでは？といった意味です。

**Comment by taxio** [comment]
fav, comment, reportはuser情報をbodyに入れなくていいように対応中です。
refs #89

**Comment by taxio** [comment]
favの登録・取り消しはboolean属性を持たせるのではなく、post・deleteを使った方がRESTに沿っているので、そっちで実装しています。
他のAPIも同様。

**Comment by pddg** [comment]
refs #91
