### ISSUE TITLE
Favと同様にReportやCommentもURLをネストしたい

### ISSUE THREAD

**Issue by pddg** [jphacks/KB_1809_2#96]
## Why

Planに関わりなくReportやCommentの一覧を取得したり投稿したりしたいシーンがない

## What

- `/plan/comments/` -> `/plan/plans/<id>/comments/`
- `/plans/reports/` -> `/plan/plans/<id>/reports/`

これまでのエンドポイントは廃止する．

**Comment by pddg** [comment]
Spotsも

- `/plan/spots/` -> `/plan/plans/<id>/spots/`

**Comment by ken-kentan** [comment]
こちら、可能であれば10/27日中に欲しいです。
よろしくおねがいします。
